---
- name: Install and configure Docker on Ubuntu
  hosts: all
  become: yes  # Ensure commands are run with sudo
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install dependancies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker's official GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      args:
        warn: false

    - name: Add Docker's official APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present

    - name: Update apt package list after adding Docker repository
      apt:
        update_cache: yes

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present

    - name: Enable Docker service to start on boot
      systemd:
        name: docker
        enabled: yes

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started

    - name: Add current user to the Docker group
      shell: usermod -aG docker ${USER}
      args:
        warn: false

    - name: Display Docker service status
      shell: systemctl status docker
      register: docker_status_output

    - name: Print Docker service status output
      debug:
        var: docker_status_output.stdout
