---
- name: Install vsftpd and configure firewall
  hosts: all
  become: yes

  tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes

    - name: Install vsftpd
      apt:
        name: vsftpd
        state: present

    - name: Backup vsftpd config
      copy:
        src: /etc/vsftpd.conf
        dest: /etc/vsftpd.conf.bak
        remote_src: yes
        backup: yes

    - name: Allow FTP ports in UFW
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 20
        - 21

    - name: Reload UFW
      command: ufw reload
      when: ansible_facts['os_family'] == 'Debian'

    - name: Ensure UFW is enabled
      ufw:
        state: enabled

    - name: Display status
      shell: ufw status
      register: ufw_status

    - debug:
        var: ufw_status.stdout
