---
all:
  hosts:
    rpi0:
      ansible_host: rpi0-server
      ansible_user: rpi0
    rpi1:
      ansible_host: rpi1-server
      ansible_user: rpi1
    kali:
      ansible_host: 192.168.1.22
      ansible_user: kali