---
all:
  hosts:
    rpi0:
      ansible_host: rpi0-server
      ansible_user: rpi0
    rpi1:
      ansible_host: rpi1-server
      ansible_user: rpi1
    rpi2:
      ansible_host: kali-server
      ansible_user: rpi2
  children:
    siem-stack:
      hosts:
        rpi0: {}
        rpi1: {}
    ids-ips:
      hosts:
        rpi0: {}
    net-sec-server:
      hosts:
        rpi1: {}
