---
all:
  hosts:
    rpi1:
      ansible_host: rpi1-server
      ansible_user: rpi1
    rpi3:
      asible_host: rpi3-server
      ansible_user: rpi3
    rpi2:
      ansible_host: rpi2
      ansible_user: rpi2
  # children:
  #   siem-stack:
  #     hosts:
  #       rpi0: {}
  #       rpi1: {}
  #   elastic-server:
  #     hosts:
  #       rpi0: {}
  #   suricata-server:
  #     hosts:
  #       rpi1: {}
