---
all:
  hosts:
    rpi1:
      ansible_host: rpi1-server
      ansible_user: rpi1
    rpi2:
      ansible_host: rpi2-server
      ansible_user: rpi2
    rpi3:
      asible_host: rpi3-server
      ansible_user: rpi3
