---
all:
  hosts:
    rpi0:
      ansible_host: rpi0-server
      ansible_user: rpi0
    rpi1:
      ansible_host: rpi1-server
      ansible_user: rpi1
    kali:
      ansible_host: kali-server
      ansible_user: kali
    main-server:
      ansible_host: main-server
  children:
    siem-server:
      hosts:
        rpi0: {}
    net-sec-server:
      hosts:
        rpi1: {}
    monitoring_server:
      hosts:
        main-server: {}