---
- name: Add Suricata PPA and Install Suricata
  hosts: suricata-server
  become: yes

  tasks:
    - name: Add the Suricata PPA repository
      apt_repository:
        repo: "ppa:oisf/suricata-stable"
        state: present
      ignore_errors: yes

    - name: Update the APT package list
      apt:
        update_cache: yes
      ignore_errors: yes

    - name: Install Suricata
      apt:
        name: suricata
        state: present

    - name: Ensure Suricata is started and enabled
      systemd:
        name: suricata
        state: started
        enabled: yes

    - name: Display Suricata version
      command: suricata --build-info
      register: suricata_info

    - name: Show Suricata version
      debug:
        msg: "{{ suricata_info.stdout_lines }}"
