---
- name: Update and Upgrade Packages
  hosts: all
  become: yes

  tasks:
    - name: Update APT package list
      apt:
        update_cache: yes

    - name: Show upgradable packages
      debug:
        var: apt_upgrade_check_before.stdout_lines

    - name: Perform distribution upgrade
      apt:
        upgrade: dist
        autoclean: yes
        autoremove: yes
